apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zi5vi0o8l-java-quarkus
  janus-idp.io/tekton: zi5vi0o8l-java-quarkus
  backstage.io/kubernetes-id: zi5vi0o8l-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zi5vi0o8l-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
